> getwd()
> NEI <- readRDS("summarySCC_PM25.rds")
> str(NEI)
> dim(NEI)
> head(NEI)
> SCC <- readRDS("Source_Classification_Code.rds")
> str(SCC)
> dim(SCC)
> head(SCC)
> TotalEmissionsYearly <- aggregate(Emissions ~ year,NEI,sum)
> png('plot1.png')
> barplot(height=TotalEmissionsYearly$Emissions,names.arg=TotalEmissionsYearly$year,xlab="Years",ylab=expression('total PM'[2.5]*' emission'),main=expression('Total PM'[2.5]*' emissions at various years'))
> dev.off()